
set(CUACC_KERNELS kernels CACHE PATH "cuacc main dir")
set(CUACC_KERNELS_DIR ${CMAKE_CURRENT_LIST_DIR} CACHE PATH "cuacc main dir")
set(CUACC_KERNELS_SRC_DIR ${CUACC_KERNELS_DIR}/src CACHE PATH "cuacc src dir")
set(CUACC_KERNELS_INCLUDE_DIR ${CUACC_KERNELS_DIR}/include CACHE PATH "cuacc include dir")
set(CUACC_KERNELS_BUILD_DIR ${CMAKE_CURRENT_BINARY_DIR} CACHE PATH "cuacc build directory")

if(UNIX)
    if("${CMAKE_BUILD_TYPE}" STREQUAL "")
        set(CMAKE_BUILD_TYPE RELEASE)
    else()
        string(TOUPPER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE)
    endif()
endif()

file(GLOB_RECURSE CUACC_KERNELS_CXX_SRC
    ${CUACC_KERNELS_SRC_DIR}/*.cpp
)
file(GLOB_RECURSE CUACC_KERNELS_CXX_HEADERS
    ${CUACC_KERNELS_SRC_DIR}/*.hpp
    ${CUACC_KERNELS_INCLUDE_DIR}/*.hpp
    ${CUACC_KERNELS_INCLUDE_DIR}/*.cuh
)

file(GLOB_RECURSE CUACC_KERNELS_CU_SRC
    ${CMAKE_CURRENT_LIST_DIR}/src/*.cu
)

add_library(${CUACC_KERNELS} STATIC ${CUACC_KERNELS_CXX_SRC} ${CUACC_KERNELS_CU_SRC})
add_library(${LIB_CUACC}::${CUACC_KERNELS} ALIAS ${CUACC_KERNELS})

target_link_libraries(${CUACC_KERNELS} PRIVATE
    cuacc::core
    cuacc::memory
    CUDA::cudart_static
    CUDA::cuda_driver
)

target_include_directories(${CUACC_KERNELS} PUBLIC
    $<BUILD_INTERFACE:${CUACC_KERNELS_INCLUDE_DIR}>
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/>
)

target_compile_options(${CUACC_KERNELS} PRIVATE
    $<$<CONFIG:RELEASE>:  -allow-unsupported-compiler ${CUACC_REL_BUILD_FLAGS} ${CUACC_REL_WARN_FLAGS} $<$<BOOL:${CUACC_TCMALLOC}>:${CUACC_TCMALLOC_FLAGS}>>
    $<$<CONFIG:DEBUG>: ${CUACC_DBG_BUILD_FLAGS} ${CUACC_DBG_WARN_FLAGS} $<$<BOOL:${CUACC_TCMALLOC}>:${CUACC_TCMALLOC_FLAGS}>>
    $<$<CONFIG:PERF>: $<$<COMPILE_LANGUAGE:CXX>: -O3 -pg -Wall -Wextra> $<$<COMPILE_LANGUAGE:CUDA>: -lineinfo> $<$<BOOL:${CUACC_TCMALLOC}>:${CUACC_TCMALLOC_FLAGS}>>
)

target_link_options(${CUACC_KERNELS} PUBLIC
    $<$<CONFIG:RELEASE>: -s $<$<BOOL:${CUACC_TCMALLOC}>:${CUACC_TCMALLOC_LINKER_FLAGS}>>
    $<$<CONFIG:DEBUG>: $<$<BOOL:${CUACC_TCMALLOC}>:${CUACC_TCMALLOC_LINKER_FLAGS}>>
)

set_target_properties(${CUACC_KERNELS} PROPERTIES
    INTERPROCEDURAL_OPTIMIZATION ON
    CXX_STANDARD ${CUACC_CXX_STANDARD}
    CXX_STANDARD_REQUIRED ON
    CXX_EXTENSIONS OFF
    CUDA_STANDARD ${CUACC_CUDA_STANDARD}
    CUDA_STANDARD_REQUIRED ON
    CUDA_EXTENSIONS OFF
    CUDA_ARCHITECTURES ${CUACC_CUDA_ARCHITECTURES}
    OUTPUT_NAME ${LIB_CUACC}-${CUACC_KERNELS}
    # VERSION ${PROJECT_VERSION}
    SOVERSION ${PROJECT_VERSION}
    # SOVERSION ${PROJECT_VERSION_MAJOR}
)

if(CUACC_INSTALL)
    install(
        TARGETS ${CUACC_KERNELS}
        EXPORT ${LIB_CUACC}_Targets
        LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
        NAMELINK_SKIP
        RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} # for windows
        ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
        INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
    )

    install(TARGETS ${CUACC_KERNELS}
        LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
        NAMELINK_ONLY
        RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} # for windows
        ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    )

    install(
        DIRECTORY ${CUACC_KERNELS_INCLUDE_DIR}/
        DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/
        FILES_MATCHING
        PATTERN "*.hpp"
        REGEX "/[^.]+$"
    )
endif(CUACC_INSTALL)
